{{- if .Values.httproute.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "hellok8s.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hellok8s.labels" . | nindent 4 }}
spec:
  hostnames:
    - {{ .Values.httproute.hostname | quote }}
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: {{ .Values.httproute.gatewayName | quote }}
      namespace: {{ .Values.httproute.gatewayNamespace | quote }}
      sectionName: {{ .Values.httproute.listenerSectionName | quote }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - group: ""
          kind: Service
          name: {{ include "hellok8s.fullname" . }}
          port: {{ .Values.service.port }}
          weight: 1
{{- end }}
